name: publish to nuget
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run:
          dotnet build -c Release "./Our.Umbraco.NodeDefender/Our.Umbraco.NodeDefender.csproj"

      - name: Release
        run:
          dotnet pack -c Release --no-build -o out "./Our.Umbraco.NodeDefender/Our.Umbraco.NodeDefender.csproj"

      - name: Publish
        run: ls .\out\*.nupkg | foreach { dotnet nuget push $_ -s https://api.nuget.org/v3/index.json -k $env:NUGET_TOKEN }
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_KEY }} 